#!/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# PixelCast — Copyright (C) 2026 Bas van Ritbergen
#
# discover-logserver.sh — mDNS-discover a PixelCast-compatible log server
# (advertising _pixelcast-log._tcp) and (re)generate the rsyslog forwarding
# drop-in accordingly. No log server anywhere in this script — fully
# generic/site-agnostic. Run periodically via PixelCast-logdiscovery.timer.
#
# Behaviour:
#   - Log server found     -> write rsyslog forward config, restart rsyslog
#                              if config changed, update status file.
#   - No log server found  -> remove rsyslog forward config if present,
#                              restart rsyslog if it changed, update status.
#   - A message is only written to the journal when the state actually
#     changes (found -> not found, or vice versa, or target changed) to
#     avoid spamming the journal on every timer tick.

set -u

SERVICE_TYPE="_pixelcast-log._tcp"
RSYSLOG_CONF="/etc/rsyslog.d/60-forward-logserver.conf"
STATE_DIR="/run/pixelcast"
STATUS_FILE="$STATE_DIR/logforward-status.json"
LAST_HOST_FILE="$STATE_DIR/logforward-last-host"

mkdir -p "$STATE_DIR"

# ── Discover ─────────────────────────────────────────────────────────────
# Resolve immediately (-r), terminate after the initial scan (-t), machine
# parsable output (-p). Take the first IPv4 resolved ("=") record.
RECORD=$(timeout 5 avahi-browse -r -t -p "$SERVICE_TYPE" 2>/dev/null \
    | awk -F';' '$1=="=" && $3=="IPv4" {print; exit}')

FOUND_HOST=""
FOUND_PORT=""
if [ -n "$RECORD" ]; then
    FOUND_HOST=$(echo "$RECORD" | awk -F';' '{print $8}')
    FOUND_PORT=$(echo "$RECORD" | awk -F';' '{print $9}')
fi

PREV_HOST=""
[ -f "$LAST_HOST_FILE" ] && PREV_HOST=$(cat "$LAST_HOST_FILE")

NOW=$(date -Iseconds)

# ── Apply ────────────────────────────────────────────────────────────────
if [ -n "$FOUND_HOST" ]; then
    NEW_CONF="# Auto-generated by discover-logserver.sh — do not edit by hand.
# Forwards all logs to the mDNS-discovered PixelCast log server.
# In-memory queue only (no queue.filename/maxdiskspace) so nothing is
# ever spooled to disk if the network is briefly unavailable.
action(
    type=\"omfwd\"
    target=\"${FOUND_HOST}\"
    port=\"${FOUND_PORT}\"
    protocol=\"tcp\"
    action.resumeRetryCount=\"-1\"
    queue.type=\"linkedlist\"
    queue.size=\"10000\"
)
stop
"
    CHANGED=1
    if [ -f "$RSYSLOG_CONF" ] && [ "$(cat "$RSYSLOG_CONF")" = "$NEW_CONF" ]; then
        CHANGED=0
    fi

    if [ "$CHANGED" = "1" ]; then
        echo "$NEW_CONF" > "$RSYSLOG_CONF"
        systemctl restart rsyslog 2>/dev/null
    fi

    if [ "$PREV_HOST" != "$FOUND_HOST" ]; then
        echo "PixelCast log discovery: forwarding logs to ${FOUND_HOST}:${FOUND_PORT}"
    fi
    echo "$FOUND_HOST" > "$LAST_HOST_FILE"

    python3 -c "
import json
json.dump({
    'connected': True,
    'host': '${FOUND_HOST}',
    'port': '${FOUND_PORT}',
    'last_checked': '${NOW}',
}, open('${STATUS_FILE}', 'w'))
"
else
    if [ -f "$RSYSLOG_CONF" ]; then
        rm -f "$RSYSLOG_CONF"
        systemctl restart rsyslog 2>/dev/null
    fi

    if [ -n "$PREV_HOST" ]; then
        echo "PixelCast log discovery: no log server found on network — logging locally only"
    fi
    rm -f "$LAST_HOST_FILE"

    python3 -c "
import json
json.dump({
    'connected': False,
    'host': None,
    'port': None,
    'last_checked': '${NOW}',
}, open('${STATUS_FILE}', 'w'))
"
fi
